language: java
jdk:
  - openjdk7
script: asdf plugin-test scala https://github.com/smashedtoatoms/asdf-scala.git 'node --version'

before_script:
  - git clone https://github.com/asdf-vm/asdf.git asdf
  - . asdf/asdf.sh
os:
  - linux
